[package]
name = "rjam-merkle"
version = "0.1.0"
edition.workspace = true

[dependencies]
rjam-codec = { workspace = true }
rjam-common = { workspace = true }
rjam-crypto = { workspace = true }
thiserror = { workspace = true }