[package]
name = "fr-pvm-invocation"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
fr-codec = { workspace = true }
fr-common = { workspace = true }
fr-crypto = { workspace = true }
fr-erasure-coding = { workspace = true }
fr-merkle = { workspace = true }
fr-pvm-host = { workspace = true }
fr-pvm-interface = { workspace = true }
fr-pvm-types = { workspace = true }
fr-state = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
