[package]
name = "rjam-pvm-invocation"
version = "0.1.0"
edition.workspace = true

[dependencies]
rjam-codec = { workspace = true }
rjam-common = { workspace = true }
rjam-crypto = { workspace = true }
rjam-merkle = { workspace = true }
rjam-pvm-core = { workspace = true }
rjam-pvm-host = { workspace = true }
rjam-pvm-interface = { workspace = true }
rjam-pvm-types = { workspace = true }
rjam-state = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
