[package]
name = "fr-pvm-invocation"
version = "0.1.0"
edition.workspace = true

[dependencies]
fr-codec = { workspace = true }
fr-common = { workspace = true }
fr-crypto = { workspace = true }
fr-merkle = { workspace = true }
fr-pvm-core = { workspace = true }
fr-pvm-host = { workspace = true }
fr-pvm-interface = { workspace = true }
fr-pvm-types = { workspace = true }
fr-state = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
