[package]
name = "rjam-pvm-hostcall"
version = "0.1.0"
edition = "2021"

[dependencies]
rjam-codec = { workspace = true }
rjam-common = { workspace = true }
rjam-crypto = { workspace = true }
rjam-state = { workspace = true }
rjam-pvm-core = { workspace = true }
thiserror = { workspace = true }