[package]
name = "rjam-block"
version = "0.1.0"
edition = "2021"

[dependencies]
rjam-codec = { workspace = true, features = ["derive"] }
rjam-common = { workspace = true }
rjam-extrinsics = { workspace = true }
