[package]
name = "rjam-transition"
version = "0.1.0"
edition = "2021"

[dependencies]
rjam-codec = { workspace = true }
rjam-common = { workspace = true }
rjam-crypto = { workspace = true }
rjam-types = { workspace = true }
rjam-state = { workspace = true }
ark-ec-vrfs = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }