[package]
name = "rjam-transition"
version = "0.1.0"
edition = "2021"

[dependencies]
rjam-block = { workspace = true }
rjam-codec = { workspace = true }
rjam-common = { workspace = true }
rjam-crypto = { workspace = true }
rjam-extrinsics = { workspace = true }
rjam-merkle = { workspace = true }
rjam-pvm-core = { workspace = true }
rjam-pvm-host = { workspace = true }
rjam-pvm-invocation = { workspace = true }
rjam-pvm-types = { workspace = true }
rjam-state = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
