[package]
name = "fr-state-merkle-v2"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
fr-common = { workspace = true }
fr-db = { workspace = true }
fr-state = { workspace = true }
bitvec = { version = "1.0.1", features = ["serde"] }
