[package]
name = "rjam-network"
version = "0.1.0"
edition.workspace = true

[dependencies]
quinn = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
tokio = { workspace = true }
