[package]
name = "rjam-pvm-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
rjam-codec = { workspace = true }
rjam-common = { workspace = true }
rjam-pvm-types = { workspace = true }
bit-vec = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
