[package]
name = "fr-pvm-core"
version.workspace = true
edition.workspace = true

[dependencies]
fr-codec = { workspace = true }
fr-common = { workspace = true }
fr-pvm-types = { workspace = true }
bit-vec = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
