[package]
name = "fr-pvm-interface"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
fr-codec = { workspace = true }
fr-common = { workspace = true }
fr-crypto = { workspace = true }
fr-pvm-core = { workspace = true }
fr-pvm-host = { workspace = true }
fr-pvm-types = { workspace = true }
fr-state = { workspace = true }
mini-moka = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
