[package]
name = "fr-state"
version = "0.1.0"
edition.workspace = true

[dependencies]
fr-block = { workspace = true }
fr-clock = { workspace = true }
fr-codec = { workspace = true }
fr-common = { workspace = true, features = ["default"] }
fr-crypto = { workspace = true }
fr-db = { workspace = true }
fr-merkle = { workspace = true }
fr-state-merkle = { workspace = true }
bit-vec = { workspace = true }
dashmap = { workspace = true }
hex = { workspace = true }
paste = { workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
