[package]
name = "rjam-state"
version = "0.1.0"
edition = "2021"

[dependencies]
rjam-block = { workspace = true }
rjam-clock = { workspace = true }
rjam-codec = { workspace = true }
rjam-common = { workspace = true, features = ["default"] }
rjam-crypto = { workspace = true }
rjam-db = { workspace = true }
rjam-merkle = { workspace = true }
rjam-state-merkle = { workspace = true }
bit-vec = { workspace = true }
dashmap = { workspace = true }
hex = { workspace = true }
paste = { workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }