[package]
name = "rjam-state"
version = "0.1.0"
edition = "2021"

[dependencies]
rjam-codec = { workspace = true }
rjam-common = { workspace = true }
rjam-crypto = { workspace = true }
rjam-db = { workspace = true }
rjam-merkle-trie = { workspace = true }
rjam-types = { workspace = true }
blake2 = { workspace = true }
bit-vec = { workspace = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }
