[package]
name = "rjam-db"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = { workspace = true }
rocksdb = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
