[package]
name = "rjam-db"
version = "0.1.0"
edition = "2021"

[dependencies]
rjam-common = { workspace = true }
rjam-crypto = { workspace = true }
dotenv = { workspace = true }
lazy_static = { workspace = true }
rocksdb = { workspace = true }
thiserror = { workspace = true }
