[package]
name = "fr-db"
version = "0.1.0"
edition.workspace = true

[dependencies]
fr-common = { workspace = true }
dashmap = { workspace = true }
rocksdb = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
