[package]
name = "rjam-node"
version = "0.1.0"
edition = "2021"

[dependencies]
rjam-block = { workspace = true }
rjam-common = { workspace = true }
rjam-db = { workspace = true }
rjam-extrinsics = { workspace = true }
rjam-state = { workspace = true }
rjam-state-merkle = { workspace = true }
rjam-transition = { workspace = true }
tokio = { workspace = true }