[package]
name = "rjam-common"
version = "0.1.0"
edition = "2021"

[dependencies]
rjam-codec = { workspace = true }
cfg-if = { workspace = true }
hex = { workspace = true }

[features]
default = ["tiny"]
tiny = []
small = []
full = []
