[package]
name = "fr-pvm-types"
version = "0.1.0"
edition.workspace = true

[dependencies]
fr-codec = { workspace = true }
fr-common = { workspace = true }
fr-limited-vec = { workspace = true }
thiserror = { workspace = true }
