[package]
name = "fr-codec"
version = "0.1.0"
edition.workspace = true

[features]
derive = ["fr-codec-derive"]

[dependencies]
fr-codec-derive = { workspace = true, optional = true }
fr-limited-vec = { workspace = true }
bit-vec = { workspace = true }
thiserror = { workspace = true }
