[package]
name = "fr-erasure-coding"
version = "0.1.0"
edition.workspace = true

[dependencies]
fr-common = { workspace = true }
rayon = { workspace = true }
reed-solomon-simd = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
