[package]
name = "jam-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
jam-common = { workspace = true }
ark-ec-vrfs = { workspace = true }
blake2 = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
