[package]
name = "rjam-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
rjam-common = { workspace = true }
ark-ec-vrfs = { workspace = true }
blake2 = { workspace = true }
hex = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
