name: CI

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install nightly toolchain
        run: rustup toolchain install nightly --component rustfmt

      - name: Check rust version
        run: rustc +nightly --version

      - name: Check formatting
        run: cargo +nightly fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        run: rustup toolchain install stable --component clippy

      - name: Check rust version
        run: rustc +stable --version

      - name: Install libclang-dev
        run: sudo apt-get install libclang-dev

      - name: Run clippy
        run: cargo +stable clippy --workspace --all-targets --all-features -- -D warnings -W clippy::all

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        run: rustup toolchain install stable

      - name: Check rust version
        run: rustc +stable --version

      - name: Install libclang-dev
        run: sudo apt-get install libclang-dev

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install nextest pre-built binary
        run: cargo binstall cargo-nextest --secure

      - name: Run tests (tiny config)
        env:
          CARGO_INCREMENTAL: "0"
        run: cargo +stable nextest run --workspace --profile ci --features tiny

      - name: Clean target directory
        run: cargo clean

      - name: Run tests (full config)
        env:
          CARGO_INCREMENTAL: "0"
        run: cargo +stable nextest run --workspace --profile ci --features full

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        run: rustup toolchain install stable --component llvm-tools-preview

      - name: Check rust version
        run: rustc +stable --version

      - name: Install libclang-dev
        run: sudo apt-get install libclang-dev

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install nextest pre-built binary
        run: cargo binstall cargo-nextest --secure

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Collect code coverage data
        env:
          CARGO_INCREMENTAL: "0"
        run: cargo +stable llvm-cov nextest --lcov --output-path lcov.info

      - name: Upload coverage data to codecov
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # pin@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: lcov.info
          fail_ci_if_error: false
