name: Dependabot PR Rust tests

on:
  pull_request:
    types:
      - opened

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        run: rustup toolchain install stable

      - name: Check rust version
        run: rustc +stable --version

      - name: Install libclang-dev
        run: sudo apt-get install libclang-dev

      - name: Install nextest pre-built binary
        run: cargo binstall cargo-nextest --secure

      - name: Run tests
        run: cargo +stable nextest run --workspace --profile ci
